# Generated by Django 5.1.7 on 2025-04-01 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Packages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("period_in_hours", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PayedTransactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phoneNumber",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?1?\\d{9,15}$", "Enter a valid phone number."
                            )
                        ],
                    ),
                ),
                ("timePayed", models.DateTimeField(auto_now_add=True)),
                ("amountPayed", models.DecimalField(decimal_places=2, max_digits=10)),
                ("package", models.CharField(max_length=255)),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["phoneNumber"], name="mikrotikapp_phoneNu_67ee0e_idx"
                    ),
                    models.Index(
                        fields=["transaction_id"], name="mikrotikapp_transac_859993_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PendingPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phoneNumber",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?1?\\d{9,15}$", "Enter a valid phone number."
                            )
                        ],
                    ),
                ),
                (
                    "macAddress",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$",
                                "Enter a valid MAC address.",
                            )
                        ],
                    ),
                ),
                ("ipAddress", models.GenericIPAddressField()),
                ("payed", models.BooleanField(default=False)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["phoneNumber", "amount"],
                        name="mikrotikapp_phoneNu_1baccc_idx",
                    )
                ],
            },
        ),
    ]
