# Generated by Django 5.1.7 on 2025-04-13 11:20

import mikrotikapp.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotikapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payedtransaction",
            name="sender_phone_number",
            field=mikrotikapp.fields.LastNineDigitsPhoneField(max_length=9),
        ),
        migrations.AlterField(
            model_name="pendingpayment",
            name="phoneNumber",
            field=mikrotikapp.fields.LastNineDigitsPhoneField(max_length=9),
        ),
        migrations.AlterField(
            model_name="sessions",
            name="phone_number",
            field=mikrotikapp.fields.LastNineDigitsPhoneField(max_length=9),
        ),
    ]
