# Generated by Django 5.1.7 on 2025-04-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotikapp", "0002_payedtransaction_delete_payedtransactions"),
    ]

    operations = [
        migrations.CreateModel(
            name="sessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="pendingpayment",
            name="macAddress",
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name="pendingpayment",
            name="phoneNumber",
            field=models.CharField(max_length=15),
        ),
    ]
