# Generated by Django 5.1.7 on 2025-04-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotikapp", "0002_alter_payedtransaction_sender_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="packages",
            name="period_in_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="packages",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
