# Generated by Django 5.1.7 on 2025-04-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotikapp", "0003_packages_period_in_minutes_alter_packages_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packages",
            name="period_in_hours",
        ),
        migrations.AlterField(
            model_name="packages",
            name="period_in_minutes",
            field=models.IntegerField(),
        ),
    ]
