# Generated by Django 5.1.7 on 2025-04-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotikapp", "0005_alter_pendingpayment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payedtransaction",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
