# Generated by Django 5.1.7 on 2025-04-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotikapp", "0006_alter_payedtransaction_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packages",
            name="price",
            field=models.IntegerField(),
        ),
    ]
