# Generated by Django 5.1.7 on 2025-04-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotikapp", "0007_alter_packages_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comand_type",
                    models.CharField(
                        choices=[
                            ("add_user", "Add User"),
                            ("login_user", "Login User"),
                            ("remove_user", "Remove User"),
                            ("update_user", "Update User"),
                        ],
                        max_length=50,
                    ),
                ),
                ("params", models.JSONField()),
                ("executed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
