# Generated by Django 5.1.7 on 2025-05-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotikapp", "0009_tickets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickets",
            name="ticketPeriod",
            field=models.IntegerField(),
        ),
    ]
