# Generated by Django 5.1.7 on 2025-05-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotikapp", "0010_alter_tickets_ticketperiod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessions",
            name="mac_address",
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
