# Generated by Django 5.1.7 on 2025-06-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotikapp', '0011_alter_sessions_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticketPassword',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticketUsername',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
