# Generated by Django 5.1.7 on 2025-06-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mikrotikapp",
            "0012_sessions_mpesa_code_alter_tickets_ticketpassword_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessions",
            name="mpesa_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
