# Generated by Django 5.1.7 on 2025-07-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotikapp', '0012_alter_tickets_ticketpassword_and_more'),
        ('mikrotikapp', '0013_alter_sessions_mpesa_code'),
    ]

    operations = [
    ]
