# Generated by Django 5.1.7 on 2025-07-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mikrotikapp", "0014_merge_20250703_1123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commands",
            name="comand_type",
            field=models.CharField(
                choices=[
                    ("add_user", "Add User"),
                    ("login_user", "Login User"),
                    ("remove_user", "Remove User"),
                    ("update_user", "Update User"),
                    ("logout_user", "Logout User"),
                ],
                max_length=50,
            ),
        ),
    ]
